/**
 * pnpm export-abi [--address 0x...]
 *
 * Writes src/lib/contracts/vault.ts with the StacksClubVault ABI from contracts/out and the
 * deployed address. Without --address it reads the latest BSC broadcast of Deploy.s.sol, then
 * falls back to NEXT_PUBLIC_VAULT_ADDRESS, then leaves the address empty.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { getAddress } from "viem";

const root = join(__dirname, "..");
const artifact = join(root, "contracts/out/StacksClubVault.sol/StacksClubVault.json");
const broadcast = join(root, "contracts/broadcast/Deploy.s.sol/56/run-latest.json");

function deployed(): { address: string | null; block: number | null } {
  const i = process.argv.indexOf("--address");
  if (i >= 0) return { address: getAddress(process.argv[i + 1]!), block: null };
  if (existsSync(broadcast)) {
    const run = JSON.parse(readFileSync(broadcast, "utf8"));
    const tx = run.transactions?.find(
      (t: { transactionType: string; contractName: string }) =>
        t.transactionType === "CREATE" && t.contractName === "StacksClubVault",
    );
    const receipt = run.receipts?.find((r: { contractAddress?: string }) => r.contractAddress);
    if (tx?.contractAddress) {
      return { address: getAddress(tx.contractAddress), block: receipt ? Number(receipt.blockNumber) : null };
    }
  }
  const env = process.env.NEXT_PUBLIC_VAULT_ADDRESS;
  return { address: env ? getAddress(env) : null, block: null };
}

if (!existsSync(artifact)) {
  console.error("Missing contracts/out. Run `cd contracts && forge build` first.");
  process.exit(1);
}
const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
const { address, block } = deployed();

mkdirSync(join(root, "src/lib/contracts"), { recursive: true });
writeFileSync(
  join(root, "src/lib/contracts/vault.ts"),
  `// Generated by scripts/export-abi.ts. Do not edit by hand.
import type { Address } from "viem";

export const VAULT_ADDRESS: Address | null = ${address ? `"${address}"` : "null"};
/** Block the vault was deployed in; event sync starts here. */
export const VAULT_DEPLOY_BLOCK: bigint | null = ${block ? `${block}n` : "null"};

export const vaultAbi = ${JSON.stringify(abi, null, 2)} as const;
`,
);
console.log(`wrote src/lib/contracts/vault.ts (address: ${address ?? "not deployed"}, block: ${block ?? "unknown"})`);
